name: SAST

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:
    workflow_call:

jobs:
    trivy:
        name: SAST (Trivy)
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Run Trivy
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                  scan-type: "fs"
                  scan-ref: "."
                  scanners: "vuln,secret,misconfig"
                  severity: "CRITICAL,HIGH"
                  exit-code: "1"
                  format: "table"
                  trivyignores: ".trivyignore"
